# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Swooned' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Swooned

  pod 'SDWebImage', '~> 4.1'
  pod 'SVProgressHUD'
  pod 'Alamofire'
  pod 'Google-Mobile-Ads-SDK'
  pod 'SwiftRangeSlider'
  pod 'YouTubePlayer'
#  pod 'HTagView'

  target 'SwoonedTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwoonedUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
